### PR TITLE
Added Kick functionality to Bot 

### PR DESCRIPTION
**Pull request by MrL1605**
Related Issue: #8 

Steps performed:
 - Bot first checks if message is sent from `private` chat. if yes then stop as there is no one to kick.
 - Then get all the mentioned users in the message
 - Get their respective `user_id`.
 - Send a `kick_chat_member` request for each user.

I have just started to learn Elixir, and Hacktober Fest was a way to accomplish that for me.
I tried my best to keep the coding style as already was.

If there are any improvements / modifications, please let me know.
Any kind of Feedback, is also welcomed as I'm completely new to Elixir.

### CODE REVIEW

**Comment by v0idpwn** [comment]
Hi! I appreaciate your help :) 
I think you aren't checking if the user who sent `/kick` is an admin, right? Could you please add this functionality so we can merge?

**Comment by MrL1605** [comment]
Sure I would add that back. 
I thought it was redundant check as Telegram API, throws an error if bot does not have permission.
Anyway I'll add it in an hour.

**Comment by v0idpwn** [comment]
No @MrL1605, I guess you didn't got me right. 

I mean checking if the user who sent the `/kick` message is an admin, or a random member could kick people through the bot.

**Comment by MrL1605** [comment]
Oh, sorry.
I'll add check for that as well.

**Comment by MrL1605** [comment]
Also, do you want me to check if Bot has permission for kicking a user or no?

**Comment by v0idpwn** [comment]
I don't think it is needed, @MrL1605, but if you already added it I see no problem.

**Comment by MrL1605** [comment]
I'm stuck at an error for some time. Could you help where I'm going wrong?
I'm running Elixir in docker (was running it before as well). I followed below steps
```
git clone https://github.com/lambda-study-group/lambdinha-bot/
mix deps.get
# Edited config/config.exs, with my test bot details
mix compile
mix server
```
On startup the app shuts down with following error.
```
14:53:28.778 [error] GenServer App.Poller terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:option, :server_only, :honor_cipher_order} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version.Requirement, Version
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    (logger) lib/logger.ex:874: Logger.truncate/2
    (logger) lib/logger.ex:689: Logger.__do_log__/3
    (app) lib/app/poller.ex:49: App.Poller.process_messages/1
    (app) lib/app/poller.ex:19: App.Poller.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Last message: {:"$gen_cast", :update}
State: 0

14:53:28.779 [info]  Application app exited: shutdown
``` 
Shouldn't these steps get me working with master branch bot?

**Comment by v0idpwn** [comment]
@MrL1605 I'd run it with just "mix". Did you try it?

**Comment by MrL1605** [comment]
Pushed the changes hoping for it work, As I'm unable to run the Bot anymore.
I'll keep trying.

**Comment by v0idpwn** [comment]
I'm able to run it normally. In fact, I just tried your branch. It works fine when the bot or the user has no permission. It has a match error when it try kicking someone,

**Comment by v0idpwn** [comment]
I fixed the first issue, now your get_mentioned_users function isn't working. Are you sure it was working before?

**Comment by MrL1605** [comment]
Yes, it was working correctly.

**Comment by MrL1605** [comment]
Got it working finally. Tested.

As my Elxir was in Docker, it was on the latest version, there's a library `hackney` which was in older version. And when `Nadia` is ran it gave following error in iex as follows: (which is visible in above stacktrace as well, but i could not decode it)
```elixir
> Nadia.get_me()
{:error,
 %Nadia.Model.Error{reason: {:option, :server_only, :honor_cipher_order}}}
``` 
 The fix is [here](https://github.com/benoitc/hackney/issues/591#issuecomment-535186928) to add following line in mix.esx dependencies
```  {:hackney, github: "benoitc/hackney", override: true} ```

I can sleep in peace now. :relieved:

**Comment by v0idpwn** [comment]
Oh, I had this issue in another application and didn't even noticed it was the same... I solved going back in elixir instead of using the most recent version of hackney.

**Comment by MrL1605** [comment]
Also found out that if an admin tries to kick an admin, API throws an error.

**Comment by anabastos** [comment]
@MrL1605 hey friend. I just fixed this issue by adding hackney to mix.
I'm not sure if it's the best solution but got it working
Thanks for your refactory!!

**Comment by v0idpwn** [comment]
@anabastos you can already use "1.15.2" instead of referencing the github repository

**Pull request merged**
